import adapter from '@sveltejs/adapter-node';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess(),
  kit: {
    // Phase 6 needs `src/routes/api/chat/+server.ts` to run as a real server-side proxy
    // (inject the owner's OpenRouter key at request time, stream the upstream response back
    // without buffering). `adapter-static` cannot host that — a static site has no request-time
    // server. `adapter-node` gives a plain Node server (no cloud-specific runtime), so the rest
    // of the site (catalog, docs, playgrounds) stays prerendered/static while the chat proxy
    // runs live. Registry JSON/tarballs under `static/registry` (generated by `build:registry`)
    // are still served as-is — adapter-node serves `static/` alongside the Node server.
    adapter: adapter(),
  },
};

export default config;
