import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { error } from '@sveltejs/kit';

import type { RequestHandler } from './$types';

/**
 * Serves the registry artifacts generated by `build:registry` (`index.json`, `{name}.json`,
 * `{name}.tar.gz`) with explicit, correct headers.
 *
 * Deliberately NOT served from `static/`, and deliberately NOT prerendered: adapter-node's
 * built-in static file server (sirv) — which also serves whatever `prerender = true` writes to
 * `build/prerendered/` — unconditionally treats any asset ending in `.gz` as a precompressed
 * sibling of the same name minus `.gz` (the mechanism meant for `foo.js.gz` next to `foo.js`).
 * For `{name}.tar.gz` that strips down to `{name}.tar`, which has no known mime type, so sirv
 * serves the tarball with an empty Content-Type and a spurious `Content-Encoding: gzip` header
 * — reproducible even when this route prerenders, because the *serving*, not the generation, is
 * where the bug lives. Running this as a live request-time endpoint (reading the same
 * build-time-generated file from `registry-data/`) sidesteps it entirely.
 */
export const prerender = false;

// A single non-slash path segment: no traversal is possible even before the explicit pattern
// check below, since `params.file` can never contain `/`.
const VALID_FILENAME = /^[a-z0-9-]+\.(?:json|tar\.gz)$/i;

function registryDataDir(): string {
  return resolve(process.cwd(), 'registry-data');
}

function contentTypeFor(file: string): string | null {
  if (file.endsWith('.tar.gz')) return 'application/gzip';
  if (file.endsWith('.json')) return 'application/json';
  return null;
}

export const GET: RequestHandler = async ({ params }) => {
  if (!VALID_FILENAME.test(params.file)) {
    throw error(404, `Invalid registry file name "${params.file}".`);
  }

  const contentType = contentTypeFor(params.file);
  if (!contentType) throw error(404, `Unsupported registry file type for "${params.file}".`);

  let raw: Buffer;
  try {
    raw = readFileSync(resolve(registryDataDir(), params.file));
  } catch {
    throw error(404, `Registry file "${params.file}" not found.`);
  }

  // Copied into a plain `ArrayBuffer` rather than passed as `Buffer`/`Uint8Array` directly:
  // `Buffer`'s `ArrayBufferLike`-parameterized type can fail to structurally match the DOM lib's
  // `BodyInit` union (it also allows `SharedArrayBuffer`, which `Response` does not accept as-is).
  // A plain `ArrayBuffer` built here is unambiguously valid `BodyInit`.
  const body = new ArrayBuffer(raw.byteLength);
  new Uint8Array(body).set(raw);

  return new Response(body, {
    headers: {
      'Content-Type': contentType,
      'Cache-Control': 'public, max-age=300',
    },
  });
};
